# https://github.com/airbnb/swift

only_rules:
  - closure_spacing
  - colon
  - empty_enum_arguments
  - extension_access_modifier
  - fatal_error_message
  # - force_cast
  - force_try
  # - force_unwrapping
  # - implicitly_unwrapped_optional
  - generic_type_name
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - operator_usage_whitespace
  - pattern_matching_keywords
  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
  - sorted_imports
  - switch_case_alignment
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_name
  - unused_closure_parameter
  - unused_optional_binding
  - vertical_whitespace
  - void_return
  - custom_rules

excluded:
  - Pods

colon:
  apply_to_dictionaries: true

indentation: 2

trailing_comma:
  mandatory_comma: true

custom_rules:
  no_objcMembers:
    name: "@objcMembers"
    regex: "@objcMembers"
    message: "Explicitly use @objc on each member you want to expose to Objective-C"
    severity: error
  # no_direct_standard_out_logs:
  #   name: "Writing log messages directly to standard out is disallowed"
  #   regex: "(\\bprint|\\bdebugPrint|\\bdump|Swift\\.print|Swift\\.debugPrint|Swift\\.dump)\\s*\\("
  #   match_kinds:
  #   - identifier
  #   message: "Don't commit `print(…)`, `debugPrint(…)`, or `dump(…)` as they write to standard out in release. Either log to a dedicated logging system or silence this warning in debug-only scenarios explicitly using `// swiftlint:disable:next no_direct_standard_out_logs`"
  #   severity: warning
